### ISSUE TITLE
OIP1 - separate bio and domestic waste

### ISSUE THREAD

**Issue by ligi** [ethdevberlin/OIPS#1]
currently it is all going to one bin - and we produce a lot of bio waste - would be great if we can separate. We just need to buy a bin for it and coordinate with the landlord on where we can dump it.

**Comment by ligi** [comment]
great to see so many thumbs up for this - we now already have a bin we can use for it ("trash" from our neighbours that moved out. Next step is @mvglasenapp talking to our landlord on Thursday

**Comment by mvglasenapp** [comment]
I made the request to the landlord who told me to ask the concierge. I've just made the request to the concierge. News coming soon

**Comment by Schaeff** [comment]
Cool any update on this?

**Comment by ligi** [comment]
yay - we now have this - thanks @mvglasenapp - closing
