### ISSUE TITLE
OIP 10: new coffee machine

### ISSUE THREAD

**Issue by mvglasenapp** [ethdevberlin/OIPS#10]
As you know, our italian expresso machine has some flaws:
- it takes time to make a coffee
- it doesn't make all kinds of coffee
- it needs quite a lot of maintenance
- ...

Imo, we should have another one, which is very simple to use and never breaks down, so with low maintenance, like following Nespresso machines: https://www.nespresso.com/pro/de/de/pages/zenius ; https://www.nespresso.com/pro/de/de/pages/gemini-CS203 

The environmental problem because of aluminium capsules should be resolvable with alternative capsules.

Any inputs?

**Comment by ligi** [comment]
I strongly signal to not buy a capsule machine as they are really bad for the environment. Please let's get something that operates on raw beans.

**Comment by mvglasenapp** [comment]
The bean grinder was actually the reason why the current machine was out of usage during 2 weeks: too difficult to use..

**Comment by ligi** [comment]
OK - still strongly signal against using a capsule machine. I could offer the following: I place my semi-automatic machine in the office (drinking mainly tea nowadays anyway) - this one is easy to use (basically just one button press) and I never had problems with the grinder.

**Comment by mvglasenapp** [comment]
Thanks for the offer ligi! I'll try anyway to find an alternative without capsules

**Comment by ligi** [comment]
Reopening - unfortunately the siemens broke.

**Comment by ligi** [comment]
closing again - the siemens works again
