### ISSUE TITLE
OIP 11: making the non-used phone cabine useful by transforming it in a power nap room

### ISSUE THREAD

**Issue by mvglasenapp** [ethdevberlin/OIPS#11]
As one of our small phone cabines is nearly never used, I'm wondering whether we could change it into a power nap room by equipping it with this i.e: https://www.home24.de/kategorie/wohnzimmermoebel/sessel/relaxliegen/?qv_parent=000000008000017335&qv_child=000000001000127854&pla_type=model2&gclid=EAIaIQobChMIx5Cok5LY5AIVleJ3Ch2Blg-_EAQYBCABEgJIkvD_BwE

It could also allow some jet laggeg visitors to crush down there if ever they didn't manage accomodation on time.

**Comment by Marenz** [comment]
I really like that idea.

**Comment by gumb0** [comment]
Awesome idea!

**Comment by leonardoalt** [comment]
Nice one @mvglasenapp !
I guess we can close it since it was done?
