### ISSUE TITLE
OIP 19 - Add "opened at" dates on milk

### ISSUE THREAD

**Issue by franzihei** [ethdevberlin/OIPS#19]
Now that we have a permanent marker next to the fridge it might make sense to quickly **write down the date on the milk container when opening a new one**. Currently, we have 2-3 (old?) open oat/almond milks and 1-2 (old?) open cow milk containers in the fridge. :( I went ahead and wrote a date on the cow milk today! Let's only open new ones when necessary and then also get rid of the old open ones in one go..?

**Comment by ligi** [comment]
I added signs and pens to the fridges - wonder if we can close this issue? Also happy about clearing out the fridges.

**Comment by franzihei** [comment]
Yes, I think we can close this. I'll have a look at the fridge in the kitchen later and clear out the "bad stuff".
