### ISSUE TITLE
OIP-22 Proper tea (+infrastructure)

### ISSUE THREAD

**Issue by ligi** [ethdevberlin/OIPS#22]
as #10 is closed now we are kinda good on coffee.
But IMHO we really lack a good tea and infrastructure for it. I actually bring my own tea from home and really dislike the tea&infrastructure we have in the office (e.g. the kettle really sucks IMHO)
Opening this issue to find out if others also would drink more tea if the tea would be good and if infrastructure would be available.
So I suggest getting the following things for infrastructure:
 * https://meileaf.com/teaware/gong-fu-code/
 * a gaiwan - perhaps as a set with some cups / gong dao bei
 * a smart water heater - e.g. Xiaomi VIOMI 4L
 * a Matcha Scoop

And then some (good bio + loose leaf) tea/tisane:
 * matcha
 * oolong
 * white/black/green
 * jiagoulan
 * roiboos
 * bamboo
 * Ginko
 * mallow blossoms

Yea - this would require a significant budget - I guess ~420€. But compared to what coffee/coffee-machine costs it is actually not that much and IMHO would greatly improve the office (maybe also save some money on the coffee side of things by reducing the amount of coffee we need and the amount of repair/maintenance of the coffee machines) 
Just putting this out there - maybe there are other tea lovers hidden in the office that just did not surface as the current tea situation is so bad.

**Comment by gumb0** [comment]
I support drinking tea, but I'm not geeking out this much yet, and not sure if anyone else does.
For example, can you explain a bit what's the point of this designer tray for £112.50?

Having a better water heater would be nice, but what's "smart" about this one?

**Comment by gumb0** [comment]
And yeah, I support having good loose leaf tea, but I don't care about herbal tea / tisane...

**Comment by ligi** [comment]
Thanks for your input @gumb0 
If you know another god tray feel free to link it here. But this one less a "designer tray" than a tray from tea lovers that went trough multiple iterations and has a lot of thought behind it. If you want their e.g. their YT channel can give some more insight - they often mention the code and use it (or the predecessor) in the sessions: https://www.youtube.com/channel/UCaHBABJFMRAtnKhQp2Cu5BQ - but also happy if you know a  good alternative - just link it here
The smart thing about the water heater is that you can freely select the temperature (which is important for some teas) It tracks when you need to care for descale (which IMHO is important in the office) and measures the TDS. Also in the end this one is more silent than the current kettle and the 4L tank is really nice as you need to refill less. But also here happy about recommendations regarding alternatives

**Comment by Marenz** [comment]
I am also a tea drinker and support more tea infrastructure, but as @gumb0 I am not geeking out on it ;)

**Comment by ligi** [comment]
I improvised something in the lounge area
