### ISSUE TITLE
OIP-29 Make upstairs hangout area nicer

### ISSUE THREAD

**Issue by franzihei** [ethdevberlin/OIPS#29]
I would love to make the hangout area in the greenhouse nicer and more cozy. It's such an amazing space which just needs a bit of more love and consistency to be even nicer!

For the short term what I would like to do is..
- Get a cover for the sofa and possibly covers for some of the pillows
- Buy 2-3 bigger plants to make the area more friendly
- Consider painting the one wall in a nice color (just like the previous tenant had it)
- Replace the old rug with a new one (the old rug would fit nicely in the armchair sitting corner in the guest area)
- Get rid of the furry white fake furs in that area (maybe they can be used elsewhere) :)
- Get 1-2 more cozy sitting "furniture" like armchairs or pouffs

For the longer term I would also like to 
- Consider getting a second sofa (replacing the old one / moving the old one downstairs)

**I am more than happy to take the lead in this if nobody else objects. :)** 

What do you guys think?

**Comment by mvglasenapp** [comment]
Sounds great! 

In order to get the ball rolling, feel free to submit an AOC "others" in KF under the cost center Berlin Office (OP_08) by listing the links of the items needing to get purchased and sharing an estimated price of the project so we can order soon

**Comment by franzihei** [comment]
Yay, amazing! I will do so soon, but since I'm currently swamped I think this will be a project for the calmer time "between the years". :)

**Comment by gumb0** [comment]
Great progress on this OIP! Thank you @rosee8 @franzihei @mvglasenapp 

Maybe should be closed already?

**Comment by franzihei** [comment]
There may be a few smaller improvements here and there, but yep, I think this can be closed!
