### ISSUE TITLE
Plan a dinner or party around Devconnect

### ISSUE THREAD

**Issue by rosee8** [ethdevberlin/OIPS#36]
Dates Devconnect: **APRIL 18-25, 2022**
https://devconnect.org/

Things to discuss:

- the date
- what food & drinks
- music
- covid policy
- list with people who wanna come

What are your ideas and thoughts?

**Comment by kuzdogan** [comment]
I guess the date was announced to be April 8th. Or is this a separate event?

**Comment by ligi** [comment]
> the date

 we already have a party at the 8th announced (e.g. in the form for DEVConnect in Discord) - likely together with chainsafe - but we should also make something after DEVconnect as some people can only come afterwards - but not before.

> what food & drinks

I can make masalla chai again and let's order the usual non alcoholic drinks - for the alcoholic drinks someone else needs to care ;-)

> music

I already asked ReMix if they can play - they like to but need to coordinate. I can do some selection and we can also do a permissionless DJing. Will also try to invite ronin-kaizen (Goerli validator and DJ)

> covid policy

hope this is not needed at the time - but we should look closer to the event. Maybe ask people to test before even though the situation is clear - but a party with masks is not great IMHO.

> list with people who wanna come

we can invite all people from the last party and maybe use our ticketh instance (tickets for free still) - just to have an overview how many are coming without having to use meetup again.

**Comment by gumb0** [comment]
I think this can be closed? (the party did happen)
