### ISSUE TITLE
Lounge improvement 

### ISSUE THREAD

**Issue by AfafOua** [ethdevberlin/OIPS#45]
Hello all, 

we were thinking about getting a new couch instead of the broken one (grey), and would like to have your opinion. 
Here are the options I found so far: 

👾 https://www.ikea.com/de/de/p/vimle-3er-sofa-mit-recamiere-gunnared-beige-s99399109/#content 

🎃  https://www.ikea.com/de/de/p/vimle-4er-sofa-mit-recamiere-gunnared-mittelgrau-s19399486/

👻  https://www.ikea.com/de/de/p/friheten-eckbettsofa-mit-bettkasten-mit-zusaetzlichen-rueckenkissen-skiftebo-dunkelgrau-s59326624/

🤩 https://www.ikea.com/de/de/p/slatorp-3er-sofa-mit-recamiere-links-tallmyra-weiss-schwarz-10471504/ 

If you like none of those let me know and we can find more options😃 Suggestions are also welcome☺️

**Comment by kuzdogan** [comment]
Do two L sofas in the lounge area work in terms of space?

**Comment by AfafOua** [comment]
> Do two L sofas in the lounge area work in terms of space?

Probably not 😅 I am looking for other options

**Comment by kuzdogan** [comment]
I bought from home24 it went smoothly. Some options: https://www.home24.de/einzelsofas/?price.max=900&width.min=160

**Comment by leonardoalt** [comment]
I vote for a sofa bed :D

**Comment by AfafOua** [comment]
> I bought from home24 it went smoothly. Some options: https://www.home24.de/einzelsofas/?price.max=900&width.min=160

Looks good, I will look for a comfortable one and then give all the options we have again!

**Comment by AfafOua** [comment]
> I vote for a sofa bed :D

We have a nap room 😴 Let us explore all the options and decide

**Comment by leonardoalt** [comment]
> We have a nap room 😴 Let us explore all the options and decide 

well... It's not the most comfortable place tbh

**Comment by AfafOua** [comment]
Hello again! I have found more sofas with bed option. Let me know what you think 😃

https://www.maisonsdumonde.com/DE/de/p/3-sitzer-sofa-clic-clac-in-gelb-elvis-186349.htm 

https://www.sklum.com/de/kaufen-schlafcouch/67827-sofa-cama-brion.html

https://www.home24.de/produkt/schlafsofa-caribe-filz-blix-senfgelb?image=2

https://www.home24.de/produkt/schlafsofa-caribe-filz-blix-blau

https://www.home24.de/produkt/schlafsofa-mid-century-ii-flachgewebe-mint

Let me know if you have any other style in mind

**Comment by kuzdogan** [comment]
I liked the first option Elvis

**Comment by franzihei** [comment]
I'm not sure if I would put a yellow sofa up there with the green wall.. maybe we could try this green tone instead? https://www.maisonsdumonde.com/DE/de/p/4-sitzer-sofa-clic-clac-in-gruen-elvis-186350.htm

**Comment by AfafOua** [comment]
> I'm not sure if I would put a yellow sofa up there with the green wall.. maybe we could try this green tone instead? https://www.maisonsdumonde.com/DE/de/p/4-sitzer-sofa-clic-clac-in-gruen-elvis-186350.htm

This colour is also nice

**Comment by rosee8** [comment]
> I'm not sure if I would put a yellow sofa up there with the green wall.. maybe we could try this green tone instead? https://www.maisonsdumonde.com/DE/de/p/4-sitzer-sofa-clic-clac-in-gruen-elvis-186350.htm

this one is nice

**Comment by kuzdogan** [comment]
Yeah the green tone would be nicer
