### ISSUE TITLE
OIP7 - Improve WiFi in the big meeting room

### ISSUE THREAD

**Issue by ligi** [ethdevberlin/OIPS#7]

**Comment by ligi** [comment]
Digged a bit into the problem as it was really unusable for the geth-to-gehter.
The root-cause of the problem seems to be that one of the switches in the server room has a problem. Was plugging directly into one of them -> worked - plugging into the other one -> did not work. The lights on the switch where lighting up. So there could be 2 things as far as I see: 
 1) uplink on this switch is broken
 2) the switch is broken
we can figure out later what exactly the problem is.

So the workaround now to get decent wifi in the meeting room was that I plugged the AP of the meeting room in the working switch.
But later on we need to care for a proper fix. This should also make more of our outlets work. 

cc @mvglasenapp

**Comment by ligi** [comment]
to fix it even better we will need a new long ethernet cable to mount the ap on the ceiling

**Comment by Marenz** [comment]
What about a simple wifi forwarder? Also, maybe not helpful here, but worth knowing about, I recently learned about this thing: https://www.asus.com/de/Networking/AiMesh-AX6100-WiFi-System-RT-AX92U-2-Pack/

**Comment by mvglasenapp** [comment]
I recall that we had a router in the conference room some time ago and everything worked well in these times. Could we maybe just set it that way again? @ligi

**Comment by ligi** [comment]
@mvglasenapp sorry did not see this reply - but this would not solve the problem with the switch mentioned here as the router would be behind the switch

**Comment by franzihei** [comment]
can probably be closed because we now have amazing WiFi?

**Comment by ligi** [comment]
true
