### ISSUE TITLE
OIP8: Make printer work for @lianahus

### ISSUE THREAD

**Issue by bshastry** [ethdevberlin/OIPS#8]
I'm unable to execute printing jobs while I'm on WiFi. However, the printer can be discovered.

**Comment by ligi** [comment]
The issue must be something different. I just printed via WiFi

**Comment by LianaHus** [comment]
same here

**Comment by bshastry** [comment]
Now it simply works :-) Editing title as required.

**Comment by Marenz** [comment]
I just checked with @LianaHus and it works for her.

**Comment by Marenz** [comment]
so this can be closed
