### ISSUE TITLE
OIP 9 - automatic office access

### ISSUE THREAD

**Issue by mvglasenapp** [ethdevberlin/OIPS#9]
I would like to set up an automation to give access to the office with i.e. following tool: https://www.pearl.de/a-NX4466-3112.shtml;jsessionid=oB72EFCE2864E1C16785633E20D23123B?vid=917&wa_id=40&wa_num=5117&utm_source=googleps&utm_medium=cpc&gclid=EAIaIQobChMIzqPCxpbV5AIVyp13Ch1lxQNcEAQYAiABEgJn3_D_BwE

Any input? @ligi & everyone

**Comment by ligi** [comment]
I have bad experiences with stuff from pearl - I would rather go with a NUKI or Abus (cheaper but no online access)
